apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-mlops
spec:
  project: default
  source:
    repoURL: https://github.com/wolfpackstatmathieu/application-deployment-api.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-mthomassin
  syncPolicy:
    automated:
      selfHeal: true